FROM node:16.13.2-alpine as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
RUN npm install --save-dev web-vitals
RUN npm install --save-dev react-router-dom

COPY . ./
RUN npm run build