services:
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build: .
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: