BASE_URL = "127.0.0.1:11434/api/chat"
MODEL_NAME = "llama3.2:1b"
# CATEGORIES = {
#     "Programming & Development": {
#         "Web Development & Design": {
#             "Web Development": {},
#             "Front End Development": {},
#             "Back End Development": {},
#             "Content Management Systems": {},
#             "PHP": {},
#             "User Experience Design": {},
#             "WordPress": {},
#             "Web Design": {},
#             "E Commerce": {},
#             "Web Servers": {},
#             "Web Hosting": {},
#             "Communications Technology": {},
#             "Mockups": {},
#             "Web Management": {},
#             "Web Graphics": {},
#             "Shopify": {},
#             "Social Networking Development": {},
#             "Text Search Engines": {},
#             "Elementor": {},
#             "Figma": {},
#             "SMS": {},
#             "Squarespace": {},
#             "Thumbnail Design": {}
#         },
#         "Programming & Software": {
#             "Programming": {},
#             "JavaScript": {},
#             "Microsoft": {},
#             "Java": {},
#             "SQL": {},
#             "API": {},
#             "Python": {},
#             "Apple Development": {},
#             "C#": {},
#             "C++": {},
#             "XML": {},
#             "Linux": {},
#             "Cloud Computing": {},
#             "Object-Oriented Programming": {},
#             "JSON": {},
#             "Version Control": {},
#             "Embedded Systems": {},
#             "Financial Services": {},
#             "Web Scraping": {},
#             "Unix": {},
#             "Open Source": {},
#             "Objective-C": {},
#             "XHTML": {},
#             "GIS": {},
#             "Perl": {}
#         },
#         "Apps & Mobile": {
#             "App & Mobile Programming": {},
#             "Responsive Web Design": {},
#             "Game Development": {},
#             "Mobile App Marketing": {}
#         },
#         "Database Design & Administration": {
#             "MySQL": {},
#             "SQL": {},
#             "Microsoft SQL Server": {},
#             "MongoDB": {},
#             "Oracle": {},
#             "Database Development": {},
#             "PostgreSQL": {},
#             "Database Design": {},
#             "Database Administration": {},
#             "SQLite": {},
#             "PL/SQL": {},
#             "Microsoft Access": {},
#             "Crystal Reports": {},
#             "Data Warehouse": {},
#             "Stored Procedures": {},
#             "Sybase": {},
#             "Query Optimization": {},
#             "FoxPro": {},
#             "Transact-SQL": {},
#             "DB2": {},
#             "Graph Database": {}
#         },
#         "Networking, Hardware & System Admin": {
#             "Networking": {},
#             "Microsoft": {},
#             "Server Administration": {},
#             "Communications Technology": {},
#             "Linux": {},
#             "Cloud Computing": {},
#             "Amazon": {},
#             "Virtualization": {},
#             "Cisco": {},
#             "Routers": {},
#             "Computer Hardware": {},
#             "SMS": {}
#         },
#         "Math / Algorithms / Analytics": {
#             "Data Analysis": {},
#             "Data Visualization": {},
#             "Analytics": {},
#             "Mathematics": {},
#             "Web Analytics": {},
#             "Microsoft Excel": {},
#             "Machine Learning": {},
#             "Algorithms": {},
#             "Regression Testing": {},
#             "Google Analytics": {},
#             "Power BI": {},
#             "Tableau": {},
#             "MATLAB": {},
#             "Data Modeling": {},
#             "Statistical Analysis": {},
#             "SAS": {},
#             "Spreadsheets": {},
#             "R Programming": {},
#             "SPSS": {},
#             "D3.js": {},
#             "Fortran": {},
#             "Oracle BI": {},
#             "IBM Cognos": {}
#         },
#         "Web / Digital Marketing": {
#             "Social Media Marketing": {},
#             "Search Engine Optimization": {},
#             "Search Engine Marketing": {},
#             "Email Marketing": {},
#             "Digital Marketing": {},
#             "Facebook Ads": {},
#             "Web Analytics": {},
#             "Mobile App Marketing": {},
#             "Landing Page Design": {},
#             "Twitter": {},
#             "Keyword Research": {},
#             "Link Building": {},
#             "LinkedIn": {},
#             "Web Content Writing": {},
#             "Google Ads": {},
#             "YouTube Marketing": {},
#             "Chatbots": {},
#             "Content Marketing": {},
#             "Instagram Marketing": {},
#             "Google Certified": {},
#             "Online Reputation Management": {},
#             "SMS Marketing": {},
#             "eBay Store Management": {},
#             "Amazon Advertising": {},
#             "Filter Design": {}
#         },
#         "Management / Leadership / Training": {
#             "IT Project Management": {},
#             "Web Management": {},
#             "Training": {},
#             "Workflow Management": {},
#             "Agile Development": {},
#             "Product Development": {},
#             "Director": {},
#             "Lifecycle Management": {},
#             "Test Driven Development": {},
#             "Product Management": {},
#             "Business Process Management": {},
#             "ITIL": {},
#             "Strategy Development": {},
#             "IT Infrastructure Design": {},
#             "Software Architecture": {},
#             "Apache Maven": {},
#             "IT Training": {},
#             "Knowledge Management": {},
#             "Waterfall Model": {},
#             "Software Configuration Management": {},
#             "Vendor Management": {},
#             "Identity and Access Management": {}
#         },
#         "Industry Specific Expertise": {
#             "Risk Management": {},
#             "Real Estate": {},
#             "Quality Assurance": {},
#             "Educational Consulting": {},
#             "Information Technology": {},
#             "Outsourcing": {},
#             "Manufacturing": {},
#             "International Business": {},
#             "Insurance Consulting": {},
#             "Construction": {},
#             "Healthcare Consulting": {},
#             "Government Industry": {},
#             "Consumer Services": {},
#             "Retail Sales": {},
#             "Energy Industry": {},
#             "Humanities": {},
#             "Environmental Industry": {},
#             "Hospitality Consulting": {},
#             "Transportation": {},
#             "Non Profit Consulting": {},
#             "Food and Beverage": {},
#             "Telecommunications Management": {},
#             "Agriculture": {},
#             "Safety Engineering": {},
#             "Sports": {}
#         },
#         "Human Resources (HR)": {
#             "Business Training": {},
#             "Human Resources Management": {},
#             "Benefits Administration": {},
#             "Staffing and Recruiting": {},
#             "Employee Management": {},
#             "Motivational Speaking": {},
#             "Compensation Management": {},
#             "Job Description Writing": {},
#             "Employee Relations": {},
#             "Employment Contracts": {},
#             "Employee Handbooks": {},
#             "Onboarding": {},
#             "Workforce Management": {},
#             "Workplace Safety": {},
#             "IT Recruiting": {},
#             "Cultural Management": {},
#             "Conflict Resolution": {},
#             "Training Material Writing": {},
#             "Communication Training": {},
#             "Safety Engineering": {},
#             "Competency Assessment": {},
#             "360 Feedback": {},
#             "Benefits Design": {},
#             "Life Insurance": {},
#             "Oracle PeopleSoft": {}
#         },
#         "ERP / CRM / SCM": {
#             "Zoho": {},
#             "Microsoft Dynamics 365": {},
#             "Salesforce": {},
#             "Odoo": {},
#             "JD Edwards": {},
#             "Zendesk": {},
#             "SugarCRM": {},
#             "Lawson": {},
#             "Oracle E-Business Suite (EBS)": {},
#             "Oracle Hyperion": {},
#             "Oracle Primavera": {},
#             "DocuSign": {},
#             "Oracle Siebel CRM": {},
#             "Oracle SCM": {},
#             "Infusionsoft": {},
#             "Baan": {}
#         },
#         "Fund Raising / Raising Capital": {
#             "Fundraising": {},
#             "Investor Management": {},
#             "Raising Equity Capital": {},
#             "Pitch Decks": {},
#             "Investor Presentations": {},
#             "Venture Capital": {},
#             "Private Equity": {},
#             "Raising Loan Capital": {},
#             "Crowdfunding": {}
#         },
#         "SAP Software": {
#             "SAP": {},
#             "SAP FICO": {},
#             "SAP Accounting": {},
#             "Wholesale Industry": {},
#             "SAP ERP": {},
#             "SAP Business One": {},
#             "SAP MM": {},
#             "SAP HANA": {},
#             "SAP BI": {},
#             "SAP SD": {},
#             "SAP Project Management": {},
#             "SAP BW": {},
#             "SAP CRM": {},
#             "SAP HR": {},
#             "SAP PP": {},
#             "SAP E-Recruiting": {},
#             "SAP BPC": {},
#             "SAP SCM": {},
#             "SAP Retail": {},
#             "SAP APO": {}
#         },
#         "Blockchain, NFT, Cryptocurrency, Tokens": {
#             "Cryptocurrency": {},
#             "Blockchain": {},
#             "Bitcoin": {},
#             "Ethereum": {},
#             "Initial Coin Offering": {},
#             "Binance": {},
#             "NFT": {},
#             "Digital Wallet": {},
#             "Altcoin": {},
#             "Smart Contracts": {},
#             "Web3": {},
#             "DApps": {},
#             "Cardano": {},
#             "Dogecoin": {},
#             "Solana": {},
#             "Tokens": {},
#             "Solidity": {},
#             "Distributed Ledger Technology": {},
#             "Harmony ONE": {},
#             "Monero XMR": {},
#             "Hyperledger": {}
#         }
#     },
#     "Education & Training": {
#         "General / Other": {
#             "Educational Instruction": {},
#             "Training": {},
#             "Tutoring": {},
#             "Online Training": {},
#             "Educational Consulting": {},
#             "E-learning Consulting": {},
#             "E-learning Development": {},
#             "Mentoring": {},
#             "Learning Management System": {},
#             "Curriculum Development": {},
#             "Tutorials": {},
#             "Instructional Design": {},
#             "Adult Education": {},
#             "Educational Research": {},
#             "Blended Learning": {},
#             "Educational Leadership": {},
#             "Competency Based Training": {},
#             "Education Facilities": {},
#             "Educational Psychology": {},
#             "Supervised Learning": {},
#             "Counselor Education": {},
#             "Multicultural Education": {},
#             "Peer Education": {},
#             "Educational Institutions": {},
#             "Educational Philosophy": {}
#         },
#         "Science & Math": {
#             "Mathematics Tutoring": {},
#             "Algebra Tutor": {},
#             "Science Teacher": {},
#             "Calculus Tutor": {},
#             "Trigonometry": {},
#             "Geometry": {},
#             "Physics Tutoring": {},
#             "Chemistry Tutoring": {},
#             "Business Mathematics": {},
#             "Scientific Research": {},
#             "Immunology": {},
#             "Environmental Education": {},
#             "Epidemiology": {},
#             "Geology": {},
#             "Astronomy": {},
#             "Toxicology": {}
#         },
#         "College / High School / Elementary": {
#             "High School Teaching": {},
#             "College Education Planning": {},
#             "Elementary Education": {},
#             "Secondary Education Teacher": {},
#             "Homeschool Teacher": {},
#             "Classroom Management": {},
#             "Early Childhood Education": {},
#             "Educational Workshops": {},
#             "Public Education": {},
#             "Continuing Education": {},
#             "Special Education Teacher": {},
#             "Higher Education Administration": {},
#             "Alternative Education": {},
#             "SAT Tutor": {},
#             "Evaluation Design": {},
#             "Common Core": {},
#             "Gifted Education": {},
#             "Autism Services": {}
#         },
#         "Information Technology & Learning Management Systems": {
#             "Information Technology": {},
#             "E-learning Consulting": {},
#             "E-learning Development": {},
#             "Educational Technology": {},
#             "IT Training": {},
#             "Technology Education": {},
#             "Learning Management System": {},
#             "Internet Training": {},
#             "Computer Software Training": {},
#             "Digital Education": {},
#             "Educational Apps": {},
#             "Educational Games": {},
#             "Articulate Rise 360": {},
#             "WordPress Learning Management System (WPLMS)": {},
#             "Cisco Training": {},
#             "Articulate Storyline": {},
#             "Adobe Captivate": {},
#             "Articulate Presenter": {},
#             "SCORM": {},
#             "Articulate Studio 360": {},
#             "LearnDash": {},
#             "Lectora": {},
#             "Chamilo": {}
#         },
#         "Languages": {
#             "English Teaching": {},
#             "Language Teacher": {},
#             "ESL Teachers": {},
#             "IELTS Teaching": {},
#             "Arabic Tutoring": {},
#             "Spanish Teaching": {},
#             "Urdu Teacher": {},
#             "French Teacher": {},
#             "Hindi Teaching": {},
#             "Indonesian Teacher": {},
#             "Chinese Tutoring": {},
#             "Russian Teacher": {},
#             "Mandarin Tutor": {},
#             "Tagalog Teacher": {},
#             "Turkish Teaching": {},
#             "German Teacher": {},
#             "Japanese Tutor": {},
#             "Portuguese Teacher": {},
#             "Italian Teacher": {},
#             "Malayalam Tutor": {},
#             "Swahili Tutor": {},
#             "Korean Tutor": {},
#             "Polish Tutor": {},
#             "Serbian Tutor": {},
#             "Vietnamese Teacher": {}
#         },
#         "Health, Fitness & Wellness": {
#             "Mental Health": {},
#             "Health Education": {},
#             "Healing": {},
#             "Health Counseling": {},
#             "Nutrition": {},
#             "Fitness Consulting": {},
#             "Personal Trainer": {},
#             "Holistic Health": {},
#             "Weight Loss Coach": {},
#             "Patient Education": {},
#             "Immunology": {},
#             "Physical Education": {},
#             "Bodybuilding Coach": {},
#             "School Health Services": {},
#             "Epidemiology": {},
#             "Clinical Training": {},
#             "First Aid Training": {},
#             "Yoga Instruction": {},
#             "Pharmacy Education": {},
#             "Dental Education": {},
#             "Therapy": {}
#         },
#         "Business & Finance": {
#             "College Education Planning": {},
#             "Business Mathematics": {},
#             "Business Education": {},
#             "Business Management Training": {},
#             "Career Coaching": {},
#             "Corporate Training": {},
#             "Communication Training": {},
#             "Executive Coaching": {},
#             "Investment Education": {},
#             "Interview Coaching": {},
#             "Financial Literacy Training": {},
#             "Enterprise Education": {},
#             "Customer Training": {},
#             "Compliance Training": {},
#             "Salesforce Training": {},
#             "Legal Education": {},
#             "SAP Training": {}
#         },
#         "Personal Growth & Family": {
#             "Mental Health": {},
#             "Healing": {},
#             "Life Coach": {},
#             "Emotional Intelligence": {},
#             "Psychological Health": {},
#             "Spiritual Healing": {},
#             "Parent Education": {},
#             "Energy Healing": {},
#             "Alternative Healing": {},
#             "Psychic Reading": {},
#             "Astrology": {},
#             "Reiki Healing": {},
#             "Tarot Card Reading": {},
#             "Horoscope": {},
#             "Guided Meditation": {},
#             "Pranic Healing": {},
#             "Chinese Astrology": {}
#         },
#         "Materials & Media": {
#             "Educational Technology": {},
#             "Educational Apps": {},
#             "Educational Writing": {},
#             "Educational Games": {},
#             "Training Material Writing": {},
#             "Educational Materials": {},
#             "Articulate Rise 360": {},
#             "Educational Video": {},
#             "Training Videos": {},
#             "Open Educational Resources": {},
#             "Educational Toys": {}
#         },
#         "Social & Behavioral Science": {
#             "Social Studies": {},
#             "Sociology": {},
#             "Social Science": {},
#             "Social Anthropology": {}
#         },
#         "Design & Art": {
#             "Design Education": {},
#             "Art Teaching": {},
#             "Music Teaching": {},
#             "Guitar Teacher": {},
#             "Jazz Education": {},
#             "Museum Education": {},
#             "Early Childhood Music Education": {},
#             "Dance Education": {},
#             "Acting Coaching": {}
#         },
#         "Sales & Marketing": {
#             "Sales Training": {},
#             "Marketing Coaching": {},
#             "Customer Service Training": {},
#             "Media Training": {},
#             "Automotive Sales Training": {}
#         },
#         "Religious": {
#             "Religious Education": {},
#             "Quran Translation Teacher": {},
#             "Jewish Education": {}
#         },
#         "Agriculture & Farming": {
#             "Agriculture": {},
#             "Agronomy": {},
#             "Agroforestry": {},
#             "Agroecology": {}
#         },
#         "Architecture & Engineering": {
#             "Engineering Education": {},
#             "Architectural Education": {}
#         }
#     }
# }


CATEGORIES = {
    "[\n\nProgramming & Development:\n  Web Development & Design:\n    Web Development: {}\n    Front End Development: {}\n    Back End Development: {}\n    Content Management Systems: {}\n    PHP: {}\n    User Experience Design: {}\n    WordPress: {}\n    Web Design: {}\n    E Commerce: {}\n    Web Servers: {}\n    Web Hosting: {}\n    Communications Technology: {}\n    Mockups: {}\n    Web Management: {}\n    Web Graphics: {}\n    Shopify: {}\n    Social Networking Development: {}\n    Text Search Engines: {}\n    Elementor: {}\n    Figma: {}\n    SMS: {}\n    Squarespace: {}\n    Thumbnail Design: {}\n  Programming & Software:\n    Programming: {}\n    JavaScript: {}\n7Microsoft: {}\n    Java: {}\n    SQL: {}\n    API: {}\n    Python: {}\n    Apple Development: {}\n    C#: {}\n    C++: {}\n    XML: {}\n    Linux: {}\n    Cloud Computing: {}\n    Object-Oriented Programming: {}\n    JSON: {}\n    Version Control: {}\n    Embedded Systems: {}\n    Financial Services: {}\n    Web Scraping: {}\n    Unix: {}\n    Open Source: {}\n    Objective-C: {}\n    XHTML: {}\n    GIS: {}\n    Perl: {}\n].\n\n"
}
LLAMA_PROMPT = "Freelancer Categories: [categories]. Project: '[project] -> [description]'. Overall Timeline: [time]. Use only the information provided below. Analyze the project and decompose it into clear, actionable subtasks. For each subtask, assign the most relevant category or categories from the given list. Output only a structured JSON array exactly following this format: [ { 'title': 'Title', 'description': 'Description', 'categories': 'Chosen category(s) from [categories]', 'budget_percentage': 'Estimated percentage of the total budget', 'approximate_time': 'Estimated time for completion of the subtask', 'id': 'Unique identifier for the subtask', 'dependencies': ['ID(s) of dependent subtasks'] } ]. Constraints: - Use exclusively the provided data; do not infer or generate any additional information. - Do not include any text or commentary outside of the JSON array. - Ensure clarity and brevity in all fields. - All subtask times must sum up to the overall project timeline [time]."
